# Generated by Django 3.2.6 on 2021-08-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210822_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wins',
            old_name='Team_won',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='wins',
            old_name='game_won',
            new_name='game_played',
        ),
        migrations.AddField(
            model_name='wins',
            name='Winner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=8),
        ),
        migrations.AddField(
            model_name='wins',
            name='scored_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
