# Generated by Django 3.2.6 on 2021-08-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210822_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wins',
            old_name='Team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='wins',
            old_name='Winner',
            new_name='winner',
        ),
    ]
