# Generated by Django 3.2.6 on 2021-08-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210822_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wins',
            new_name='Team_Scores',
        ),
    ]
