# Generated by Django 3.2.6 on 2021-08-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_wins_team_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player_scores',
            options={'verbose_name_plural': 'Player Scores'},
        ),
        migrations.AlterModelOptions(
            name='team_scores',
            options={'verbose_name_plural': 'Team_Scores'},
        ),
        migrations.RenameField(
            model_name='player_scores',
            old_name='game_scored',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='team_scores',
            old_name='game_played',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='signed_contract',
            name='player_signed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.players'),
        ),
    ]
